### ISSUE TITLE
TypeError: cannot read properties of undefined (reading 'portid')

### ISSUE THREAD

**Issue by ryanoleary26** [stogoh/network-mapper#10]
## Problem Encountered

When Nmap scans a target that has no open ports (or all ports are closed), the parse() method of NmapScan reads an undefined array of openPorts. This is because there is no check for undefined data before attempting to read port properties.

This check does exist for the array of hosts:
`175. if (host === undefined) return`

Adding a similar check should prevent this issue, and return an empty array of ports. It would be nice, for this scenario, to include closed port information as well as open ports.

## Fix
I have added a fix in #11 

Below is an example with code that produces the error.
### Nmap CLI
![Example NMAP with no ports discovered](https://user-images.githubusercontent.com/32248563/164699663-aa1e2049-f3b5-4276-b7d0-3e95266c4aef.png)
 
### Example Code:
```
import { NmapScan } from 'network-mapper'
async function main() {
    const scan = new NmapScan({
        target: ["192.168.0.14"]
    });
    const result = await scan.run();
    console.log(result);
}
main();
```

### Output:
```
PS C:\Users\Ryan\Documents\github\network-mapper-testing\clean install> node .\app.js
C:\Users\Ryan\Documents\github\network-mapper-testing\clean install\node_modules\network-mapper\lib\scans\nmap-scan\NmapScan.js:236
                                number: Number(port['portid']),
                                                   ^

TypeError: Cannot read properties of undefined (reading 'portid')
    at C:\Users\Ryan\Documents\github\network-mapper-testing\clean install\node_modules\network-mapper\lib\scans\nmap-scan\NmapScan.js:236:52
    at Array.forEach (<anonymous>)
    at C:\Users\Ryan\Documents\github\network-mapper-testing\clean install\node_modules\network-mapper\lib\scans\nmap-scan\NmapScan.js:234:35
    at Array.forEach (<anonymous>)
    at NmapScan.parse (C:\Users\Ryan\Documents\github\network-mapper-testing\clean install\node_modules\network-mapper\lib\scans\nmap-scan\NmapScan.js:174:19)
    at NmapScan.run (C:\Users\Ryan\Documents\github\network-mapper-testing\clean install\node_modules\network-mapper\lib\scans\nmap-scan\NmapScan.js:24:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (file:///C:/Users/Ryan/Documents/github/network-mapper-testing/clean%20install/app.js:9:20)

Node.js v17.6.0
```

**Comment by ryanoleary26** [comment]
Merged in #11 to dev branch, closing.
